In [1]:
# Prepared as shown in a you-tube channel
import pandas as pd

In [2]:
df=pd.read_csv("lndataset.csv")

In [3]:
df.head()

Text  language
0  klement gottwaldi surnukeha palsameeriti ning ...  Estonian
1  sebes joseph pereira thomas  på eng the jesuit...   Swedish
2  ถนนเจริญกรุง อักษรโรมัน thanon charoen krung เ...      Thai
3  விசாகப்பட்டினம் தமிழ்ச்சங்கத்தை இந்துப் பத்திர...     Tamil
4  de spons behoort tot het geslacht haliclona en...     Dutch

In [4]:
df.shape

(22000, 2)

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [6]:
tf=TfidfVectorizer(use_idf=True,norm='l2',smooth_idf=True)
y=df.language.values
x=tf.fit_transform(df["Text"].values.astype('U'))

In [7]:
y[1]

'Swedish'

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [9]:
y[1]

17

In [10]:
y[0:10]

array([ 4, 17, 19, 18,  2,  8, 20, 10, 21,  8])

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1,shuffle=False)

In [13]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

In [14]:
lr.fit(x_train,y_train)

c:\users\siddhartha borpuzari\appdata\local\programs\python\python36\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
c:\users\siddhartha borpuzari\appdata\local\programs\python\python36\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
test=["Je suis un indien"]
test_result=tf.transform(test)
lr.predict(test_result)

array([1])

In [16]:
test1=["sɔ̌ːŋ pʰîː kʰít ʔēːŋ ʔâ"]
test_result1=tf.transform(test1)
lr.predict(test_result1)

array([1])

In [17]:
test2=["हिंदू परंपरा के प्रतिष्ठित देवताओं में से एक, श्री गणेश को शुभता और नई शुरुआत का देवता माना जाता है"]
test_result2=tf.transform(test2)
lr.predict(test_result2)

array([6])